"""Shared constants, data loading, and helpers for all dashboard pages."""

import json
import os

import pandas as pd
import requests
import streamlit as st
from googleapiclient.discovery import build
from google.oauth2 import service_account
from google.oauth2.credentials import Credentials

# ── Constants ─────────────────────────────────────────────────────────────────
SHEET_ID = "1NjPJKswE2rXFnXsCah5Kv4tiSEi88jlGLnZwfHsp5o4"
SCOPES   = ["https://www.googleapis.com/auth/spreadsheets.readonly"]

PRODUCT_MAP = {
    "Wisewell Model 1 Subscription":              ("Machine", "Model 1"),
    "Wisewell Model 1 Subscription (with AMC)":   ("Machine", "Model 1"),
    "Wisewell Nano + Subscription":               ("Machine", "Nano+"),
    "Wisewell Nano + Subscription (with AMC)":    ("Machine", "Nano+"),
    "Wisewell Bubble Subscription":               ("Machine", "Bubble"),
    "Wisewell Bubble Subscription + Holiday Set": ("Machine", "Bubble"),
    "Wisewell Bubble Ownership + Holiday Set":    ("Machine", "Bubble"),
    "Wisewell Flat Subscription":                 ("Machine", "Flat"),
    "Wisewell Nano Subscription":                 ("Machine", "Nano Tank"),
    "Filter Subscription":                        ("Filter",  "Model 1"),
    "Filter Subscription (Model 1)":              ("Filter",  "Model 1"),
    "Filter Subscription (Nano+)":                ("Filter",  "Nano+"),
    "Wisewell Bubble Care+ Plan":                 ("Filter",  "Bubble"),
}

PRODUCT_ORDER  = ["Model 1", "Nano+", "Bubble", "Flat", "Nano Tank"]
CATEGORY_COLOR = {"Machine": "#0ea5e9", "Filter": "#10b981"}
MARKET_COLOR   = {"UAE": "#6366f1", "KSA": "#f59e0b"}
FX_FALLBACK    = {"AED": 1 / 3.6725, "SAR": 1 / 3.75}

SHARED_CSS = """
<style>
div[data-testid="metric-container"] {
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 12px;
    padding: 1rem 1.25rem;
}
[data-testid="stMetricValue"] { font-size: 1.55rem; font-weight: 700; }
[data-testid="stMetricLabel"] { font-size: 0.78rem; color: #64748b;
                                 text-transform: uppercase; letter-spacing: .05em; }
#MainMenu, footer { visibility: hidden; }
</style>
"""


# ── Data loading (cached — shared across all pages in the same session) ───────

def get_credentials():
    """
    Return Google credentials.
    - Cloud (Streamlit Community Cloud): reads the service account JSON
      stored under st.secrets["GOOGLE_SERVICE_ACCOUNT"].
    - Local: falls back to token.json generated by auth.py.
    """
    try:
        info = json.loads(st.secrets["GOOGLE_SERVICE_ACCOUNT"])
        return service_account.Credentials.from_service_account_info(info, scopes=SCOPES)
    except (KeyError, FileNotFoundError):
        token_path = os.path.join(os.path.dirname(__file__), "token.json")
        return Credentials.from_authorized_user_file(token_path, SCOPES)


@st.cache_data(ttl=300, show_spinner="Syncing with Google Sheets…")
def load_raw_data():
    """Fetch ACTIVE rows from both Recharge tabs and compute ARR in local currency."""
    creds   = get_credentials()
    service = build("sheets", "v4", credentials=creds)

    frames = []
    for tab, currency in [("Recharge - UAE", "AED"), ("Recharge - KSA", "SAR")]:
        rows = (
            service.spreadsheets().values()
            .get(spreadsheetId=SHEET_ID, range=tab)
            .execute()
            .get("values", [])
        )
        max_cols = max(len(r) for r in rows)
        padded   = [r + [""] * (max_cols - len(r)) for r in rows]
        df       = pd.DataFrame(padded[1:], columns=padded[0])
        df["market"]   = "UAE" if currency == "AED" else "KSA"
        df["currency"] = currency
        frames.append(df)

    df = pd.concat(frames, ignore_index=True)
    df = df[df["status"] == "ACTIVE"].copy()

    df["recurring_price"]           = pd.to_numeric(df["recurring_price"],           errors="coerce").fillna(0)
    df["quantity"]                  = pd.to_numeric(df["quantity"],                  errors="coerce").fillna(1)
    df["charge_interval_frequency"] = pd.to_numeric(df["charge_interval_frequency"], errors="coerce").fillna(1)

    # freq=30 → 30-day cycle → treat as monthly
    df["charge_interval_frequency"] = df["charge_interval_frequency"].apply(
        lambda x: 1 if x == 30 else x
    )

    df["arr_local"] = df["recurring_price"] * df["quantity"] * (12 / df["charge_interval_frequency"])

    df["category"] = df["product_title"].map(lambda t: PRODUCT_MAP.get(t, (None, None))[0])
    df["product"]  = df["product_title"].map(lambda t: PRODUCT_MAP.get(t, (None, None))[1])
    df = df[df["category"].notna()].copy()
    return df


@st.cache_data(ttl=3600, show_spinner=False)
def get_fx():
    """Live USD conversion rates for AED and SAR (cached 1 hour)."""
    try:
        r     = requests.get("https://open.er-api.com/v6/latest/USD", timeout=5)
        rates = r.json().get("rates", {})
        return {"AED": 1 / rates["AED"], "SAR": 1 / rates["SAR"], "source": "live"}
    except Exception:
        return {**FX_FALLBACK, "source": "fallback (fixed peg)"}


def apply_fx(df, fx):
    df = df.copy()
    df["arr_usd"] = df.apply(lambda r: r["arr_local"] * fx[r["currency"]], axis=1)
    return df


def fmt_usd(v):
    if v >= 1_000_000:
        return f"${v / 1_000_000:.2f}M"
    if v >= 1_000:
        return f"${v / 1_000:.1f}K"
    return f"${v:,.0f}"


def sidebar_filters(refresh_key: str):
    """Render the shared sidebar and return (market_sel, category_sel)."""
    with st.sidebar:
        st.image(
            "https://cdn.prod.website-files.com/63e6996dee5c3840d6a4b55a/"
            "63e699c0a3ce5e6d68c11b15_Wisewell%20Logo%20White.svg",
            width=160,
        )
        st.markdown("---")
        st.header("Filters")
        market_sel   = st.radio("Market",   ["All", "UAE", "KSA"],        index=0, key=f"mkt_{refresh_key}")
        category_sel = st.radio("Category", ["All", "Machine", "Filter"], index=0, key=f"cat_{refresh_key}")
        st.markdown("---")
        if st.button("↻ Force refresh", use_container_width=True, key=f"btn_{refresh_key}"):
            st.cache_data.clear()
            st.rerun()
        st.caption("Auto-refreshes every 5 min")
    return market_sel, category_sel
