"""Shared constants, data loading, and helpers for all dashboard pages."""

import json
import os

import pandas as pd
import requests
import streamlit as st
from googleapiclient.discovery import build
from google.oauth2 import service_account
from google.oauth2.credentials import Credentials

# ── Constants ─────────────────────────────────────────────────────────────────
SHEET_ID = "1NjPJKswE2rXFnXsCah5Kv4tiSEi88jlGLnZwfHsp5o4"
SCOPES   = ["https://www.googleapis.com/auth/spreadsheets.readonly"]

PRODUCT_MAP = {
    "Wisewell Model 1 Subscription":              ("Machine", "Model 1"),
    "Wisewell Model 1 Subscription (with AMC)":   ("Machine", "Model 1"),
    "Wisewell Nano + Subscription":               ("Machine", "Nano+"),
    "Wisewell Nano + Subscription (with AMC)":    ("Machine", "Nano+"),
    "Wisewell Bubble Subscription":               ("Machine", "Bubble"),
    "Wisewell Bubble Subscription + Holiday Set": ("Machine", "Bubble"),
    "Wisewell Bubble Ownership + Holiday Set":    ("Machine", "Bubble"),
    "Wisewell Flat Subscription":                 ("Machine", "Flat"),
    "Wisewell Nano Subscription":                 ("Machine", "Nano Tank"),
    "Filter Subscription":                        ("Filter",  "Model 1"),
    "Filter Subscription (Model 1)":              ("Filter",  "Model 1"),
    "Filter Subscription (Nano+)":                ("Filter",  "Nano+"),
    "Wisewell Bubble Care+ Plan":                 ("Filter",  "Bubble"),
}

PRODUCT_ORDER  = ["Model 1", "Nano+", "Bubble", "Flat", "Nano Tank"]
CATEGORY_COLOR = {"Machine": "#0ea5e9", "Filter": "#10b981"}
MARKET_COLOR   = {"UAE": "#6366f1", "KSA": "#f59e0b"}
FX_FALLBACK    = {"AED": 1 / 3.6725, "SAR": 1 / 3.75, "USD": 1.0}

SHARED_CSS = """
<style>
div[data-testid="metric-container"] {
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 12px;
    padding: 1rem 1.25rem;
}
[data-testid="stMetricValue"] { font-size: 1.55rem; font-weight: 700; }
[data-testid="stMetricLabel"] { font-size: 0.78rem; color: #64748b;
                                 text-transform: uppercase; letter-spacing: .05em; }
#MainMenu, footer { visibility: hidden; }
</style>
"""


# ── Data loading (cached — shared across all pages in the same session) ───────

def get_credentials():
    """
    Return Google credentials.
    - Cloud (Streamlit Community Cloud): reads the service account JSON
      stored under st.secrets["GOOGLE_SERVICE_ACCOUNT"].
    - Local: falls back to token.json generated by auth.py.
    """
    try:
        info = json.loads(st.secrets["GOOGLE_SERVICE_ACCOUNT"])
        return service_account.Credentials.from_service_account_info(info, scopes=SCOPES)
    except (KeyError, FileNotFoundError):
        token_path = os.path.join(os.path.dirname(__file__), "token.json")
        return Credentials.from_authorized_user_file(token_path, SCOPES)


@st.cache_data(ttl=300, show_spinner="Syncing with Google Sheets…")
def load_raw_data():
    """Fetch ACTIVE rows from both Recharge tabs and compute ARR in local currency."""
    creds   = get_credentials()
    service = build("sheets", "v4", credentials=creds)

    frames = []
    for tab, currency, market in [
        ("Recharge - UAE", "AED", "UAE"),
        ("Recharge - KSA", "SAR", "KSA"),
        ("Recharge - USA", "USD", "USA"),
    ]:
        rows = (
            service.spreadsheets().values()
            .get(spreadsheetId=SHEET_ID, range=tab)
            .execute()
            .get("values", [])
        )
        if len(rows) < 2:
            continue
        max_cols = max(len(r) for r in rows)
        padded   = [r + [""] * (max_cols - len(r)) for r in rows]
        df       = pd.DataFrame(padded[1:], columns=padded[0])
        df["market"]   = market
        df["currency"] = currency
        frames.append(df)

    df = pd.concat(frames, ignore_index=True)
    df = df[df["status"] == "ACTIVE"].copy()

    df["recurring_price"]           = pd.to_numeric(df["recurring_price"],           errors="coerce").fillna(0)
    df["quantity"]                  = pd.to_numeric(df["quantity"],                  errors="coerce").fillna(1)
    df["charge_interval_frequency"] = pd.to_numeric(df["charge_interval_frequency"], errors="coerce").fillna(1)

    # freq=30 → 30-day cycle → treat as monthly
    df["charge_interval_frequency"] = df["charge_interval_frequency"].apply(
        lambda x: 1 if x == 30 else x
    )

    df["arr_local"] = df["recurring_price"] * df["quantity"] * (12 / df["charge_interval_frequency"])

    df["category"] = df["product_title"].map(lambda t: PRODUCT_MAP.get(t, (None, None))[0])
    df["product"]  = df["product_title"].map(lambda t: PRODUCT_MAP.get(t, (None, None))[1])
    df = df[df["category"].notna()].copy()
    return df


@st.cache_data(ttl=3600, show_spinner=False)
def get_fx():
    """Live USD conversion rates for AED and SAR (cached 1 hour)."""
    try:
        r     = requests.get("https://open.er-api.com/v6/latest/USD", timeout=5)
        rates = r.json().get("rates", {})
        return {"AED": 1 / rates["AED"], "SAR": 1 / rates["SAR"], "USD": 1.0, "source": "live"}
    except Exception:
        return {**FX_FALLBACK, "source": "fallback (fixed peg)"}


def apply_fx(df, fx):
    df = df.copy()
    df["arr_usd"] = df.apply(lambda r: r["arr_local"] * fx[r["currency"]], axis=1)
    return df


def fmt_usd(v):
    if v >= 1_000_000:
        return f"${v / 1_000_000:.2f}M"
    if v >= 1_000:
        return f"${v / 1_000:.1f}K"
    return f"${v:,.0f}"


# ── Sales-specific constants ───────────────────────────────────────────────────

PRODUCT_COLOR = {
    "Model 1":   "#8b5cf6",
    "Nano+":     "#0ea5e9",
    "Bubble":    "#f43f5e",
    "Flat":      "#10b981",
    "Nano Tank": "#f59e0b",
    "Filter":    "#94a3b8",
    "Others":    "#94a3b8",
}

# Shopify unit columns: (product_name, ownership_col, subscription_col)
SHOPIFY_UNIT_COLS = [
    ("Model 1",   "Units - Model 1 (Own)", "Units - Model 1 (Sub)"),
    ("Nano+",     "Units - Nano+ (Own)",   "Units - Nano+ (Sub)"),
    ("Bubble",    "Units - Bubble (Own)",  "Units - Bubble (Sub)"),
    ("Flat",      "Units - Flat (Own)",    "Units - Flat (Sub)"),
    ("Nano Tank", "Units - Nano (Own)",    "Units - Nano (Sub)"),
]


def _shopify_product_from_name(name: str):
    """Fallback: infer (category, product) from Shopify Lineitem name."""
    n = name.lower()
    if "filter subscription (nano+)" in n:   return "Filter", "Nano+"
    if "filter subscription (model 1)" in n: return "Filter", "Model 1"
    if "bubble care+" in n or "care+ plan" in n: return "Filter", "Bubble"
    if "filter subscription" in n:           return "Filter", "Model 1"
    if "model 1" in n:   return "Machine", "Model 1"
    if "nano +" in n or "nano+" in n: return "Machine", "Nano+"
    if "bubble" in n:    return "Machine", "Bubble"
    if "flat" in n:      return "Machine", "Flat"
    if "nano" in n:      return "Machine", "Nano Tank"
    return None, "Unknown"


@st.cache_data(ttl=300, show_spinner="Syncing Shopify orders…")
def load_all_shopify():
    """Load all Shopify tabs → long DataFrame: country, date, product, category, qty."""
    creds = get_credentials()
    svc   = build("sheets", "v4", credentials=creds)
    tabs  = [("Shopify - UAE", "UAE"), ("Shopify - KSA", "KSA"), ("Shopify - USA", "USA")]
    frames = []
    for tab_name, country in tabs:
        rows = (
            svc.spreadsheets().values()
            .get(spreadsheetId=SHEET_ID, range=f"'{tab_name}'")
            .execute().get("values", [])
        )
        if len(rows) < 2:
            continue
        headers = [h.strip() for h in rows[0]]
        if headers and headers[0] in ("", " "):
            headers[0] = "Order ID"
        n      = len(headers)
        padded = [r[:n] + [""] * max(0, n - len(r)) for r in rows[1:]]
        df     = pd.DataFrame(padded, columns=headers)

        df["date"] = pd.to_datetime(
            df.get("Created at", ""), errors="coerce"
        ).dt.normalize()

        records = []
        for _, row in df.iterrows():
            product, category, qty = "Unknown", None, 0
            # Primary: unit columns (machine products)
            for prod, own_col, sub_col in SHOPIFY_UNIT_COLS:
                try:    own_v = int(str(row.get(own_col, 0) or 0))
                except: own_v = 0
                try:    sub_v = int(str(row.get(sub_col, 0) or 0))
                except: sub_v = 0
                if sub_v > 0 or own_v > 0:
                    product, category, qty = prod, "Machine", max(sub_v, own_v)
                    break
            # Fallback: parse Lineitem name (catches filter subs etc.)
            if product == "Unknown":
                lineitem = str(row.get("Lineitem name", ""))
                category, product = _shopify_product_from_name(lineitem)
                if product != "Unknown":
                    try:    qty = max(1, int(str(row.get("Lineitem quantity", 1) or 1)))
                    except: qty = 1
            records.append((product, category, qty))

        if not records:
            continue
        prods, cats, qtys = zip(*records)
        df["product"], df["category"], df["qty"] = prods, cats, qtys
        df = df[df["product"] != "Unknown"].copy()
        df["country"] = country
        frames.append(df[["country", "date", "product", "category", "qty"]])

    if not frames:
        return pd.DataFrame(columns=["country", "date", "product", "category", "qty"])
    return pd.concat(frames, ignore_index=True)


@st.cache_data(ttl=300, show_spinner=False)
def load_recharge_cancellations():
    """Load all Recharge rows (active + cancelled) for cancellation rate computation."""
    creds = get_credentials()
    svc   = build("sheets", "v4", credentials=creds)
    frames = []
    for tab, market in [("Recharge - UAE", "UAE"), ("Recharge - KSA", "KSA"), ("Recharge - USA", "USA")]:
        rows = (
            svc.spreadsheets().values()
            .get(spreadsheetId=SHEET_ID, range=tab)
            .execute().get("values", [])
        )
        if len(rows) < 2:
            continue
        max_cols = max(len(r) for r in rows)
        padded   = [r + [""] * (max_cols - len(r)) for r in rows]
        df       = pd.DataFrame(padded[1:], columns=padded[0])
        df["market"] = market
        frames.append(df)
    df = pd.concat(frames, ignore_index=True)
    df["cancelled_at_dt"] = pd.to_datetime(
        df["cancelled_at"].str.strip(), format="%d/%m/%Y", errors="coerce"
    )
    df["is_true_cancel"] = df["True Cancellation"].apply(
        lambda x: str(x).strip() == "1"
    )
    df["category"] = df["product_title"].map(
        lambda t: PRODUCT_MAP.get(t, (None, None))[0]
    )
    df["product"] = df["product_title"].map(
        lambda t: PRODUCT_MAP.get(t, (None, None))[1]
    )
    return df[["subscription_id", "market", "status", "product_title",
               "category", "product", "cancelled_at_dt", "is_true_cancel"]]


@st.cache_data(ttl=300, show_spinner=False)
def load_user_base_current():
    """
    Returns the most recent user base snapshot per country from Monthly User Base tab.
    User base = active subscriptions + cumulative owners (owners never churn).

    Row layout (0-indexed):
      3  → Global Ending User Base
      19 → UAE Total User Base (subscribers + owners)
      35 → KSA Total User Base (subscribers + owners)
    """
    creds = get_credentials()
    svc   = build("sheets", "v4", credentials=creds)
    vals  = (
        svc.spreadsheets().values()
        .get(spreadsheetId=SHEET_ID, range="'Monthly User Base'")
        .execute().get("values", [])
    )
    header = vals[0]
    col_idxs = [i for i, h in enumerate(header[1:], start=1)
                if h and not h.startswith("--")]

    def latest_nonzero(row_idx):
        row = vals[row_idx] if row_idx < len(vals) else []
        val = 0
        for ci in col_idxs:
            try:
                v = int(str(row[ci]).replace(",", "")) if ci < len(row) and row[ci] else 0
                if v > 0:
                    val = v
            except Exception:
                pass
        return val

    return {
        "global": latest_nonzero(3),
        "UAE":    latest_nonzero(19),
        "KSA":    latest_nonzero(35),
    }


@st.cache_data(ttl=300, show_spinner=False)
def load_monthly_sales_raw():
    """Return raw values of the Monthly Sales tab (list-of-lists, cached)."""
    creds = get_credentials()
    svc   = build("sheets", "v4", credentials=creds)
    return (
        svc.spreadsheets().values()
        .get(spreadsheetId=SHEET_ID, range="'Monthly Sales'")
        .execute().get("values", [])
    )


def monthly_sales_series(vals, country="All", product="All"):
    """
    Extract (months_list, values_list) from raw Monthly Sales tab data.

    Row layout (0-indexed in vals):
      3  → Total Gross Sales (global)
      6-10  → UAE Sub  (Model 1 … Nano Tank)
      13-17 → UAE Own  (Model 1 … Nano Tank)
      20    → Total UAE Sales
      24-28 → KSA Sub  (Model 1 … Nano Tank)
      31-35 → KSA Own  (Model 1 … Nano Tank)
      38    → Total KSA Sales
      63    → Paid Ads Spend (historical marketing spend)
    """
    if not vals:
        return [], []

    header = vals[0]
    months, col_idxs = [], []
    for i, h in enumerate(header[1:], start=1):
        if h and not h.startswith("--"):
            months.append(h)
            col_idxs.append(i)

    def row_vals(ri):
        if ri >= len(vals): return [0] * len(months)
        row = vals[ri]
        out = []
        for ci in col_idxs:
            try:    out.append(int(row[ci]) if ci < len(row) and row[ci] else 0)
            except: out.append(0)
        return out

    def sum_rows(*indices):
        result = [0] * len(months)
        for ri in indices:
            for j, v in enumerate(row_vals(ri)):
                result[j] += v
        return result

    pi = PRODUCT_ORDER.index(product) if product in PRODUCT_ORDER else -1

    # USA has no history in Monthly Sales tab — live Shopify only
    if country not in ("All", "UAE", "KSA"):
        return [], []

    if country == "All" and product == "All": return months, row_vals(3)
    if country == "UAE" and product == "All": return months, row_vals(20)
    if country == "KSA" and product == "All": return months, row_vals(38)
    if pi < 0:                                return months, row_vals(3)
    if country == "UAE":  return months, sum_rows(6 + pi, 13 + pi)
    if country == "KSA":  return months, sum_rows(24 + pi, 31 + pi)
    # All countries, specific product
    return months, sum_rows(6 + pi, 13 + pi, 24 + pi, 31 + pi)


@st.cache_data(ttl=300, show_spinner=False)
def load_dashboard_kpis():
    """Read pre-computed global KPIs from Dashboard Summary row 1."""
    creds = get_credentials()
    svc   = build("sheets", "v4", credentials=creds)
    rows  = (
        svc.spreadsheets().values()
        .get(spreadsheetId=SHEET_ID, range="'Dashboard Summary'!A1:AB2")
        .execute().get("values", [])
    )
    if len(rows) < 2:
        return {}
    data = rows[1]
    def sg(i): return data[i] if i < len(data) else ""
    return {
        "monthly_target":    sg(10),  # col K
        "cac":               sg(19),  # col T
        "cancellation_rate": sg(14),  # col O
        "arr":               sg(12),  # col M
        "user_base":         sg(13),  # col N
    }


def sidebar_filters(refresh_key: str):
    """Render the shared sidebar and return (market_sel, category_sel)."""
    with st.sidebar:
        st.image(
            "https://cdn.prod.website-files.com/63e6996dee5c3840d6a4b55a/"
            "63e699c0a3ce5e6d68c11b15_Wisewell%20Logo%20White.svg",
            width=160,
        )
        st.markdown("---")
        st.header("Filters")
        market_sel   = st.radio("Market",   ["All", "UAE", "KSA"],        index=0, key=f"mkt_{refresh_key}")
        category_sel = st.radio("Category", ["All", "Machine", "Filter"], index=0, key=f"cat_{refresh_key}")
        st.markdown("---")
        if st.button("↻ Force refresh", use_container_width=True, key=f"btn_{refresh_key}"):
            st.cache_data.clear()
            st.rerun()
        st.caption("Auto-refreshes every 5 min")
    return market_sel, category_sel
